### ISSUE TITLE
Got runtime error on flutter 2.8.1

### ISSUE THREAD

**Issue by blackbusters** [santa112358/widget_marker_google_map#1]
Hi, 

I tried using this plugin, but when I run the example code using flutter 2.8.1, i got runtime error :

E/flutter (27100): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Concurrent modification during iteration: Instance(length:2) of '_GrowableList'.
E/flutter (27100): #0      ListIterator.moveNext (dart:_internal/iterable.dart:336)
E/flutter (27100): #1      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081)
E/flutter (27100): #2      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
E/flutter (27100): #3      _rootRun (dart:async/zone.dart:1428)
E/flutter (27100): #4      _CustomZone.run (dart:async/zone.dart:1328)
E/flutter (27100): #5      _CustomZone.runGuarded (dart:async/zone.dart:1236)
E/flutter (27100): #6      _invoke (dart:ui/hooks.dart:150)
E/flutter (27100): #7      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
E/flutter (27100): #8      _drawFrame (dart:ui/hooks.dart:114)
E/flutter (27100):
E/flutter (27100): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (27100): #0      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:3157)
E/flutter (27100): #1      _MarkerGeneratorState._convertToMarker (package:widget_marker_google_map/src/components/marker_generator.dart:28)
E/flutter (27100): #2      _MarkerGeneratorState.onBuildCompleted.<anonymous closure> (package:widget_marker_google_map/src/components/marker_generator.dart:52)
E/flutter (27100): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
E/flutter (27100): #4      ListIterator.moveNext (dart:_internal/iterable.dart:342)
E/flutter (27100): #5      Future.wait (dart:async/future.dart:471)
E/flutter (27100): #6      _MarkerGeneratorState.onBuildCompleted (package:widget_marker_google_map/src/components/marker_generator.dart:52)
E/flutter (27100): #7      _MarkerGeneratorState.initState.<anonymous closure> (package:widget_marker_google_map/src/components/marker_generator.dart:43)
E/flutter (27100): #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145)
E/flutter (27100): #9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
E/flutter (27100): #10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
E/flutter (27100): #11     _rootRun (dart:async/zone.dart:1428)
E/flutter (27100): #12     _CustomZone.run (dart:async/zone.dart:1328)
E/flutter (27100): #13     _CustomZone.runGuarded (dart:async/zone.dart:1236)
E/flutter (27100): #14     _invoke (dart:ui/hooks.dart:150)
E/flutter (27100): #15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
E/flutter (27100): #16     _drawFrame (dart:ui/hooks.dart:114)
E/flutter (27100):

Is there any way to fix it?

Thank you.

**Comment by SaudElabdullah** [comment]
Hello sir,
I have the same issue, Did you solve it?

**Comment by santa112358** [comment]
@SaudElabdullah 
Does it also happen on version 0.0.2? If so, I will fix this problem.

Thank you.

**Comment by SaudElabdullah** [comment]
@santa112358 
Yes, It happen in version 0.0.2.

Thank you.

**Comment by WieFel** [comment]
+1 same here.
I spent a long time thinking that this was caused by my own code...

Please fix asap
